# Generated by Django 2.2.5 on 2019-09-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='launch_sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('coordinates', models.CharField(max_length=30)),
                ('operational', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('of', models.CharField(max_length=30)),
                ('launches', models.CharField(max_length=30)),
                ('heaviest', models.CharField(max_length=30)),
                ('rocket', models.CharField(max_length=30)),
                ('launched', models.CharField(max_length=30)),
                ('highest', models.CharField(max_length=30)),
                ('achieved', models.CharField(max_length=30)),
                ('altitude', models.CharField(max_length=30)),
                ('notes', models.CharField(max_length=30)),
            ],
        ),
    ]
