# Generated by Django 2.2.5 on 2019-09-15 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launch_information', '0002_auto_20190915_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='launch_sites',
            options={'verbose_name_plural': 'launch_sites'},
        ),
    ]
