# Generated by Django 2.2.5 on 2019-09-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launch_information', '0003_auto_20190915_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_dates', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('live_online_URL', models.CharField(max_length=100)),
                ('information', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Upcomings',
            },
        ),
        migrations.AlterField(
            model_name='launch_sites',
            name='achieved',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='launch_sites',
            name='altitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='launch_sites',
            name='coordinates',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='launch_sites',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='launch_sites',
            name='heaviest',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='launch_sites',
            name='highest',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='launch_sites',
            name='launched',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='launch_sites',
            name='launches',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='launch_sites',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='launch_sites',
            name='notes',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='launch_sites',
            name='number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='launch_sites',
            name='of',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='launch_sites',
            name='operational',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='launch_sites',
            name='rocket',
            field=models.CharField(max_length=100),
        ),
    ]
