# Generated by Django 2.2.5 on 2019-09-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launch_information', '0004_auto_20190915_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastLaunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_dates', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('information', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Upcomings',
            },
        ),
        migrations.RenameModel(
            old_name='launch_sites',
            new_name='LaunchSites',
        ),
    ]
