# Generated by Django 2.2.5 on 2019-09-15 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launch_information', '0005_auto_20190915_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastlaunch',
            options={'verbose_name_plural': 'PastLaunch'},
        ),
    ]
