# Generated by Django 2.2.5 on 2019-09-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launch_information', '0006_auto_20190915_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchSiteData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=130)),
                ('coordinates', models.CharField(max_length=50)),
                ('no_of_rockets_launched', models.IntegerField(null=True)),
                ('heavies_rocket_launched', models.IntegerField(null=True)),
                ('highest_altitude_achieved', models.CharField(max_length=15, null=True)),
                ('operational_date', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RocketLaunchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('date', models.CharField(max_length=20, null=True)),
                ('time', models.CharField(max_length=40, null=True)),
                ('country', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=100)),
                ('des', models.TextField(null=True)),
                ('live_url', models.URLField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LaunchSites',
        ),
        migrations.DeleteModel(
            name='PastLaunch',
        ),
        migrations.DeleteModel(
            name='Upcoming',
        ),
    ]
