# Generated by Django 2.2.5 on 2019-09-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launch_information', '0007_auto_20190915_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchsitedata',
            name='heavies_rocket_launched',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='launchsitedata',
            name='no_of_rockets_launched',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
