# Generated by Django 2.2.5 on 2019-09-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launch_information', '0008_auto_20190915_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocketlaunchdata',
            name='img',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='images/'),
        ),
    ]
