# Generated by Django 2.2.5 on 2019-09-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launch_information', '0009_rocketlaunchdata_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocketlaunchdata',
            name='img',
            field=models.ImageField(default='images/None/no-img.jpg', upload_to='static/images/'),
        ),
    ]
