# Generated by Django 2.2.5 on 2019-09-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launch_information', '0010_auto_20190915_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('text', models.TextField(unique=True)),
                ('img', models.CharField(max_length=70, null=True)),
            ],
        ),
    ]
