# Generated by Django 2.2.5 on 2019-09-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launch_information', '0014_learn_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousLaunchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('date', models.CharField(max_length=20, null=True)),
                ('time', models.CharField(max_length=40, null=True)),
                ('vehicle', models.CharField(max_length=40, null=True)),
                ('agency', models.CharField(max_length=40, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
